name: Production Build and Deploy
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node.js
        uses: actions/setup-node@v2

      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: 'build'

      - name: Build
        run: |
          cd build
          git checkout main
          git pull https://github.com/molly-firebolt/shiny-garbanzo.git main
          git push origin


      - name: Checkout Staging Target
        uses: actions/checkout@v2
        with:
          repository: molly-firebolt/fireboltdocs2guru
          token: ${{ secrets.PAT }}
          path: 'deploy'
      
      - name: Push files to target
        run: |
          cp -r build/* deploy
          cd deploy
          git add .
          git commit -m $GITHUB_SHA
          git push