name: Production Build and Deploy
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git config pull.ff only  
      
      - name: Checkout Staging Target
        uses: actions/checkout@v2
        with:
          repository: molly-firebolt/fireboltdocs2guru
          token: ${{ secrets.PAT }}
      
      - name: Push files to target
        run: |
          git checkout main;
          git pull https://github.com/molly-firebolt/shiny-garbanzo.git main;
          git push origin;